// data.js - Static data for the application

export const expressionDatabase = {
	level1: [
		"Q = A AND B",
		"Q = A OR B",
		"Q = NOT A",
		"Q = NOT B",
	],
	level2: [
		"Q = (A AND B) AND C",
		"Q = (A AND B) OR C",
		"Q = (A AND C) AND B",
		"Q = (A AND C) OR B",
		"Q = (A OR B) AND C",
		"Q = (A OR B) OR C",
		"Q = (A OR C) AND B",
		"Q = (A OR C) OR B",
		"Q = (B AND C) AND A",
		"Q = (B AND C) OR A",
		"Q = (B OR C) AND A",
		"Q = (B OR C) OR A",
		"Q = A AND (B AND C)",
		"Q = A AND (B OR C)",
		"Q = A AND (C AND B)",
		"Q = A AND (C OR B)",
		"Q = A OR (B AND C)",
		"Q = A OR (B OR C)",
		"Q = A OR (C AND B)",
		"Q = A OR (C OR B)",
		"Q = B AND (A AND C)",
		"Q = B AND (A OR C)",
		"Q = B AND (C AND A)",
		"Q = B AND (C OR A)",
		"Q = B OR (A AND C)",
		"Q = B OR (A OR C)",
		"Q = B OR (C AND A)",
		"Q = B OR (C OR A)",
		"Q = C AND (A AND B)",
		"Q = C AND (A OR B)",
		"Q = C AND (B AND A)",
		"Q = C AND (B OR A)",
		"Q = C OR (A AND B)",
		"Q = C OR (A OR B)",
		"Q = C OR (B AND A)",
		"Q = C OR (B OR A)",
		'Q = NOT (NOT A)',
		"Q = NOT (A OR B)",
		"Q = NOT (A AND B)",
	],
	// Designed for Name That mode
	level2NoOverlap: [
		"Q = (A AND B) AND C",
		"Q = (A AND B) OR C",
		"Q = (A AND C) OR B",
		"Q = (A OR B) AND C",
		"Q = (A OR B) OR C",
		"Q = (A OR C) AND B",
		"Q = (A OR C) OR B",
		"Q = (B AND C) OR A",
		"Q = (B OR C) AND A",
		"Q = (B OR C) OR A",
		"Q = A OR (B AND C)",
		"Q = A OR (B OR C)",
		"Q = A OR (C AND D)",
		"Q = A OR (D OR B)",
		"Q = B AND (A OR C)",
		"Q = B OR (A OR A)",
		"Q = C AND (A OR B)",
		"Q = B AND (B OR A)",
		'Q = NOT (NOT A)',
		"Q = NOT (A OR B)",
		"Q = NOT (A AND B)",
	],
	level3: [
		'Q = (A AND B) OR (C AND D)',
		'Q = (A OR B) AND (C OR D)',
		'Q = (A AND B) AND (C OR D)',
		'Q = (A OR B) OR (C AND D)',
		'Q = (NOT (A AND B)) OR C',
		'Q = (NOT (A OR B)) AND C',
		'Q = A AND (NOT (B OR C))',
		'Q = A OR (NOT (B AND C))',
		'Q = (NOT A) AND (NOT B)',
		'Q = (NOT A) OR (NOT B)',
		'Q = ((NOT A) AND B) OR C',
		'Q = (A AND (NOT B)) OR C',
		'Q = ((NOT A) OR B) AND C',
		'Q = (A OR (NOT B)) AND C',
		'Q = NOT ((NOT A) AND B)',
		'Q = NOT (A AND (NOT B))',
		'Q = (A AND B) OR (NOT C)',
		'Q = (A OR B) AND (NOT C)',
		'Q = (NOT A) AND (B OR C)',
		'Q = (NOT A) OR (B AND C)',
		'Q = ((NOT A) AND (NOT B)) AND C',
		'Q = ((NOT A) OR (NOT B)) OR C',
		'Q = (A AND (NOT B)) AND C',
		'Q = (A OR (NOT B)) OR C',
		'Q = NOT ((A OR B) OR C)',
		'Q = NOT ((A AND B) AND C)',
		'Q = ((A AND (NOT B)) OR C)',
		'Q = ((A OR (NOT B)) AND C)'
	],
	level4: [
		'Q = ((A AND B) OR (C AND D)) OR E',
		'Q = (A AND (B OR C)) AND (D OR E)',
		'Q = ((A OR B) AND (C AND D)) OR E',
		'Q = (A OR (B AND C)) OR (D AND E)',
		'Q = (NOT (A AND B)) OR (C AND D)',
		'Q = (A AND B) AND (NOT (C OR D))',
		'Q = ((NOT A) OR B) AND (C OR (NOT D))',
		'Q = (A AND ((NOT B) OR C)) OR (D AND E)'
	]
};