/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Old_unitconverterRouteImport } from './routes/old_unitconverter'
import { Route as Old_multiplechoiceRouteImport } from './routes/old_multiplechoice'
import { Route as Old_filesizeRouteImport } from './routes/old_filesize'
import { Route as Old_capacitycalculatorRouteImport } from './routes/old_capacitycalculator'
import { Route as IndexRouteImport } from './routes/index'

const Old_unitconverterRoute = Old_unitconverterRouteImport.update({
  id: '/old_unitconverter',
  path: '/old_unitconverter',
  getParentRoute: () => rootRouteImport,
} as any)
const Old_multiplechoiceRoute = Old_multiplechoiceRouteImport.update({
  id: '/old_multiplechoice',
  path: '/old_multiplechoice',
  getParentRoute: () => rootRouteImport,
} as any)
const Old_filesizeRoute = Old_filesizeRouteImport.update({
  id: '/old_filesize',
  path: '/old_filesize',
  getParentRoute: () => rootRouteImport,
} as any)
const Old_capacitycalculatorRoute = Old_capacitycalculatorRouteImport.update({
  id: '/old_capacitycalculator',
  path: '/old_capacitycalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/old_capacitycalculator': typeof Old_capacitycalculatorRoute
  '/old_filesize': typeof Old_filesizeRoute
  '/old_multiplechoice': typeof Old_multiplechoiceRoute
  '/old_unitconverter': typeof Old_unitconverterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/old_capacitycalculator': typeof Old_capacitycalculatorRoute
  '/old_filesize': typeof Old_filesizeRoute
  '/old_multiplechoice': typeof Old_multiplechoiceRoute
  '/old_unitconverter': typeof Old_unitconverterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/old_capacitycalculator': typeof Old_capacitycalculatorRoute
  '/old_filesize': typeof Old_filesizeRoute
  '/old_multiplechoice': typeof Old_multiplechoiceRoute
  '/old_unitconverter': typeof Old_unitconverterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/old_capacitycalculator'
    | '/old_filesize'
    | '/old_multiplechoice'
    | '/old_unitconverter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/old_capacitycalculator'
    | '/old_filesize'
    | '/old_multiplechoice'
    | '/old_unitconverter'
  id:
    | '__root__'
    | '/'
    | '/old_capacitycalculator'
    | '/old_filesize'
    | '/old_multiplechoice'
    | '/old_unitconverter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Old_capacitycalculatorRoute: typeof Old_capacitycalculatorRoute
  Old_filesizeRoute: typeof Old_filesizeRoute
  Old_multiplechoiceRoute: typeof Old_multiplechoiceRoute
  Old_unitconverterRoute: typeof Old_unitconverterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/old_unitconverter': {
      id: '/old_unitconverter'
      path: '/old_unitconverter'
      fullPath: '/old_unitconverter'
      preLoaderRoute: typeof Old_unitconverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old_multiplechoice': {
      id: '/old_multiplechoice'
      path: '/old_multiplechoice'
      fullPath: '/old_multiplechoice'
      preLoaderRoute: typeof Old_multiplechoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old_filesize': {
      id: '/old_filesize'
      path: '/old_filesize'
      fullPath: '/old_filesize'
      preLoaderRoute: typeof Old_filesizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old_capacitycalculator': {
      id: '/old_capacitycalculator'
      path: '/old_capacitycalculator'
      fullPath: '/old_capacitycalculator'
      preLoaderRoute: typeof Old_capacitycalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Old_capacitycalculatorRoute: Old_capacitycalculatorRoute,
  Old_filesizeRoute: Old_filesizeRoute,
  Old_multiplechoiceRoute: Old_multiplechoiceRoute,
  Old_unitconverterRoute: Old_unitconverterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
