/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteexpressionRouteImport } from './routes/writeexpression'
import { Route as TruthtableRouteImport } from './routes/truthtable'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as NamethatRouteImport } from './routes/namethat'
import { Route as DrawcircuitRouteImport } from './routes/drawcircuit'
import { Route as IndexRouteImport } from './routes/index'

const WriteexpressionRoute = WriteexpressionRouteImport.update({
  id: '/writeexpression',
  path: '/writeexpression',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthtableRoute = TruthtableRouteImport.update({
  id: '/truthtable',
  path: '/truthtable',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const NamethatRoute = NamethatRouteImport.update({
  id: '/namethat',
  path: '/namethat',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawcircuitRoute = DrawcircuitRouteImport.update({
  id: '/drawcircuit',
  path: '/drawcircuit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drawcircuit': typeof DrawcircuitRoute
  '/namethat': typeof NamethatRoute
  '/scenario': typeof ScenarioRoute
  '/truthtable': typeof TruthtableRoute
  '/writeexpression': typeof WriteexpressionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drawcircuit': typeof DrawcircuitRoute
  '/namethat': typeof NamethatRoute
  '/scenario': typeof ScenarioRoute
  '/truthtable': typeof TruthtableRoute
  '/writeexpression': typeof WriteexpressionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drawcircuit': typeof DrawcircuitRoute
  '/namethat': typeof NamethatRoute
  '/scenario': typeof ScenarioRoute
  '/truthtable': typeof TruthtableRoute
  '/writeexpression': typeof WriteexpressionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drawcircuit'
    | '/namethat'
    | '/scenario'
    | '/truthtable'
    | '/writeexpression'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drawcircuit'
    | '/namethat'
    | '/scenario'
    | '/truthtable'
    | '/writeexpression'
  id:
    | '__root__'
    | '/'
    | '/drawcircuit'
    | '/namethat'
    | '/scenario'
    | '/truthtable'
    | '/writeexpression'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawcircuitRoute: typeof DrawcircuitRoute
  NamethatRoute: typeof NamethatRoute
  ScenarioRoute: typeof ScenarioRoute
  TruthtableRoute: typeof TruthtableRoute
  WriteexpressionRoute: typeof WriteexpressionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writeexpression': {
      id: '/writeexpression'
      path: '/writeexpression'
      fullPath: '/writeexpression'
      preLoaderRoute: typeof WriteexpressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truthtable': {
      id: '/truthtable'
      path: '/truthtable'
      fullPath: '/truthtable'
      preLoaderRoute: typeof TruthtableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namethat': {
      id: '/namethat'
      path: '/namethat'
      fullPath: '/namethat'
      preLoaderRoute: typeof NamethatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawcircuit': {
      id: '/drawcircuit'
      path: '/drawcircuit'
      fullPath: '/drawcircuit'
      preLoaderRoute: typeof DrawcircuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawcircuitRoute: DrawcircuitRoute,
  NamethatRoute: NamethatRoute,
  ScenarioRoute: ScenarioRoute,
  TruthtableRoute: TruthtableRoute,
  WriteexpressionRoute: WriteexpressionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
