/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteexpressionRouteImport } from './routes/writeexpression'
import { Route as TruthtableRouteImport } from './routes/truthtable'
import { Route as Old_unitconverterRouteImport } from './routes/old_unitconverter'
import { Route as Old_multiplechoiceRouteImport } from './routes/old_multiplechoice'
import { Route as Old_filesizeRouteImport } from './routes/old_filesize'
import { Route as Old_capacitycalculatorRouteImport } from './routes/old_capacitycalculator'
import { Route as NamethatRouteImport } from './routes/namethat'
import { Route as DrawcircuitRouteImport } from './routes/drawcircuit'
import { Route as IndexRouteImport } from './routes/index'

const WriteexpressionRoute = WriteexpressionRouteImport.update({
  id: '/writeexpression',
  path: '/writeexpression',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthtableRoute = TruthtableRouteImport.update({
  id: '/truthtable',
  path: '/truthtable',
  getParentRoute: () => rootRouteImport,
} as any)
const Old_unitconverterRoute = Old_unitconverterRouteImport.update({
  id: '/old_unitconverter',
  path: '/old_unitconverter',
  getParentRoute: () => rootRouteImport,
} as any)
const Old_multiplechoiceRoute = Old_multiplechoiceRouteImport.update({
  id: '/old_multiplechoice',
  path: '/old_multiplechoice',
  getParentRoute: () => rootRouteImport,
} as any)
const Old_filesizeRoute = Old_filesizeRouteImport.update({
  id: '/old_filesize',
  path: '/old_filesize',
  getParentRoute: () => rootRouteImport,
} as any)
const Old_capacitycalculatorRoute = Old_capacitycalculatorRouteImport.update({
  id: '/old_capacitycalculator',
  path: '/old_capacitycalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const NamethatRoute = NamethatRouteImport.update({
  id: '/namethat',
  path: '/namethat',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawcircuitRoute = DrawcircuitRouteImport.update({
  id: '/drawcircuit',
  path: '/drawcircuit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drawcircuit': typeof DrawcircuitRoute
  '/namethat': typeof NamethatRoute
  '/old_capacitycalculator': typeof Old_capacitycalculatorRoute
  '/old_filesize': typeof Old_filesizeRoute
  '/old_multiplechoice': typeof Old_multiplechoiceRoute
  '/old_unitconverter': typeof Old_unitconverterRoute
  '/truthtable': typeof TruthtableRoute
  '/writeexpression': typeof WriteexpressionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drawcircuit': typeof DrawcircuitRoute
  '/namethat': typeof NamethatRoute
  '/old_capacitycalculator': typeof Old_capacitycalculatorRoute
  '/old_filesize': typeof Old_filesizeRoute
  '/old_multiplechoice': typeof Old_multiplechoiceRoute
  '/old_unitconverter': typeof Old_unitconverterRoute
  '/truthtable': typeof TruthtableRoute
  '/writeexpression': typeof WriteexpressionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drawcircuit': typeof DrawcircuitRoute
  '/namethat': typeof NamethatRoute
  '/old_capacitycalculator': typeof Old_capacitycalculatorRoute
  '/old_filesize': typeof Old_filesizeRoute
  '/old_multiplechoice': typeof Old_multiplechoiceRoute
  '/old_unitconverter': typeof Old_unitconverterRoute
  '/truthtable': typeof TruthtableRoute
  '/writeexpression': typeof WriteexpressionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drawcircuit'
    | '/namethat'
    | '/old_capacitycalculator'
    | '/old_filesize'
    | '/old_multiplechoice'
    | '/old_unitconverter'
    | '/truthtable'
    | '/writeexpression'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drawcircuit'
    | '/namethat'
    | '/old_capacitycalculator'
    | '/old_filesize'
    | '/old_multiplechoice'
    | '/old_unitconverter'
    | '/truthtable'
    | '/writeexpression'
  id:
    | '__root__'
    | '/'
    | '/drawcircuit'
    | '/namethat'
    | '/old_capacitycalculator'
    | '/old_filesize'
    | '/old_multiplechoice'
    | '/old_unitconverter'
    | '/truthtable'
    | '/writeexpression'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawcircuitRoute: typeof DrawcircuitRoute
  NamethatRoute: typeof NamethatRoute
  Old_capacitycalculatorRoute: typeof Old_capacitycalculatorRoute
  Old_filesizeRoute: typeof Old_filesizeRoute
  Old_multiplechoiceRoute: typeof Old_multiplechoiceRoute
  Old_unitconverterRoute: typeof Old_unitconverterRoute
  TruthtableRoute: typeof TruthtableRoute
  WriteexpressionRoute: typeof WriteexpressionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writeexpression': {
      id: '/writeexpression'
      path: '/writeexpression'
      fullPath: '/writeexpression'
      preLoaderRoute: typeof WriteexpressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truthtable': {
      id: '/truthtable'
      path: '/truthtable'
      fullPath: '/truthtable'
      preLoaderRoute: typeof TruthtableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old_unitconverter': {
      id: '/old_unitconverter'
      path: '/old_unitconverter'
      fullPath: '/old_unitconverter'
      preLoaderRoute: typeof Old_unitconverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old_multiplechoice': {
      id: '/old_multiplechoice'
      path: '/old_multiplechoice'
      fullPath: '/old_multiplechoice'
      preLoaderRoute: typeof Old_multiplechoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old_filesize': {
      id: '/old_filesize'
      path: '/old_filesize'
      fullPath: '/old_filesize'
      preLoaderRoute: typeof Old_filesizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old_capacitycalculator': {
      id: '/old_capacitycalculator'
      path: '/old_capacitycalculator'
      fullPath: '/old_capacitycalculator'
      preLoaderRoute: typeof Old_capacitycalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namethat': {
      id: '/namethat'
      path: '/namethat'
      fullPath: '/namethat'
      preLoaderRoute: typeof NamethatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawcircuit': {
      id: '/drawcircuit'
      path: '/drawcircuit'
      fullPath: '/drawcircuit'
      preLoaderRoute: typeof DrawcircuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawcircuitRoute: DrawcircuitRoute,
  NamethatRoute: NamethatRoute,
  Old_capacitycalculatorRoute: Old_capacitycalculatorRoute,
  Old_filesizeRoute: Old_filesizeRoute,
  Old_multiplechoiceRoute: Old_multiplechoiceRoute,
  Old_unitconverterRoute: Old_unitconverterRoute,
  TruthtableRoute: TruthtableRoute,
  WriteexpressionRoute: WriteexpressionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
